{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:12:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:9:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"level":"error","message":"An error occurred while processing documents: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.employmentStatus\" must be one of [UNEMPLOYED, SELF_EMPLOYED, BUSINESS_OWNER, EMPLOYED]","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.position\" must be one of [MID_MANAGER, TOP_MANAGER, WORKER, OWNER]","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.workExperienceTotal\" must be greater than or equal to 12","service":"user-service"}
{"level":"error","message":"Ошибка: TypeError: Cannot read properties of null (reading 'requestedAmount')","service":"user-service"}
{"level":"error","message":"Error occurred: Cannot read properties of null (reading 'requestedAmount')","service":"user-service"}
{"level":"error","message":"Error occurred: \"middleName\" length must be at least 2 characters long","service":"user-service"}
{"level":"error","message":"Error occurred: \"passportSeries\" length must be 4 characters long","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.employmentStatus\" must be one of [UNEMPLOYED, SELF_EMPLOYED, BUSINESS_OWNER, EMPLOYED]","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.position\" must be one of [MID_MANAGER, TOP_MANAGER, WORKER, OWNER]","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.workExperienceTotal\" must be greater than or equal to 12","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.employmentStatus\" must be one of [UNEMPLOYED, SELF_EMPLOYED, BUSINESS_OWNER, EMPLOYED]","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{\"amount\":50000,\"term\":24,\"firstName\":\"Johnatan\",\"lastName\":\"Doom\",\"middleName\":\"Mid\",\"birthdate\":\"1985-10-15T00:00:00.000Z\",\"passportSeries\":\"0001\",\"passportNumber\":\"456789\",\"gender\":\"MALE\",\"passportIssueDate\":\"2022-01-15\",\"passportIssueBranch\":\"New York Branch\",\"maritalStatus\":\"SINGLE\",\"dependentNumber\":2,\"employment\":{\"employmentStatus\":\"UNEMPLOYED\",\"employerINN\":\"123456789\",\"salary\":50000,\"position\":\"MID_MANAGER\",\"workExperienceTotal\":15,\"workExperienceCurrent\":3},\"account\":\"370998765313659809099867\",\"isInsuranceEnabled\":true,\"isSalaryClient\":false}","env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"559","Content-Type":"application/json","User-Agent":"axios/1.4.0"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://api-conveyer:3001/conveyor/calculation","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (file:///usr/src/app/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///usr/src/app/node_modules/axios/lib/adapters/http.js:570:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","status":400}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{\"amount\":50000,\"term\":24,\"firstName\":\"Johnatan\",\"lastName\":\"Doom\",\"middleName\":\"Mid\",\"birthdate\":\"1985-10-15T00:00:00.000Z\",\"passportSeries\":\"0001\",\"passportNumber\":\"456789\",\"gender\":\"MALE\",\"passportIssueDate\":\"2022-01-15\",\"passportIssueBranch\":\"New York Branch\",\"maritalStatus\":\"SINGLE\",\"dependentNumber\":2,\"employment\":{\"employmentStatus\":\"UNEMPLOYED\",\"employerINN\":\"123456789\",\"salary\":50000,\"position\":\"MID_MANAGER\",\"workExperienceTotal\":15,\"workExperienceCurrent\":3},\"account\":\"370998765313659809099867\",\"isInsuranceEnabled\":true,\"isSalaryClient\":false}","env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"559","Content-Type":"application/json","User-Agent":"axios/1.4.0"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://api-conveyer:3001/conveyor/calculation","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (file:///usr/src/app/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///usr/src/app/node_modules/axios/lib/adapters/http.js:570:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","status":400}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{\"amount\":50000,\"term\":24,\"firstName\":\"Johnatan\",\"lastName\":\"Doom\",\"middleName\":\"Mid\",\"birthdate\":\"1985-10-15T00:00:00.000Z\",\"passportSeries\":\"0001\",\"passportNumber\":\"456789\",\"gender\":\"MALE\",\"passportIssueDate\":\"2022-01-15\",\"passportIssueBranch\":\"New York Branch\",\"maritalStatus\":\"SINGLE\",\"dependentNumber\":2,\"employment\":{\"employmentStatus\":\"UNEMPLOYED\",\"employerINN\":\"123456789\",\"salary\":50000,\"position\":\"MID_MANAGER\",\"workExperienceTotal\":15,\"workExperienceCurrent\":3},\"account\":\"370998765313659809099867\",\"isInsuranceEnabled\":true,\"isSalaryClient\":false}","env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"559","Content-Type":"application/json","User-Agent":"axios/1.4.0"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://api-conveyer:3001/conveyor/calculation","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (file:///usr/src/app/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///usr/src/app/node_modules/axios/lib/adapters/http.js:570:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","status":400}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Ошибка: AxiosError: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error occurred: Request failed with status code 400","service":"user-service"}
{"level":"error","message":"Error sending code: Code must be a 6-digit string","service":"user-service"}
{"level":"error","message":"Error sending code: Code must be a 6-digit string","service":"user-service"}
{"level":"error","message":"Error sending code: Your code is incorrect.","service":"user-service"}
{"level":"error","message":"Error occurred: \"passportSeries\" length must be 4 characters long","service":"user-service"}
{"code":"23503","constraint":"fk_application_application_status","detail":"Key (status)=(PREAPPROVAL) is not present in table \"application_status\".","file":"ri_triggers.c","length":306,"level":"error","line":"2596","message":"Error calculating loan offer insert or update on table \"application\" violates foreign key constraint \"fk_application_application_status\"","name":"error","query":"INSERT INTO application(client_id, creation_date, status) VALUES(144, '2023-08-07T11:32:14.035+00:00', 'PREAPPROVAL') RETURNING application_id","routine":"ri_ReportViolation","schema":"public","service":"user-service","severity":"ERROR","stack":"error: insert or update on table \"application\" violates foreign key constraint \"fk_application_application_status\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","table":"application"}
{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:12:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:9:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"level":"error","name":"ConflictError","service":"user-service","statusCode":409}
{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:13:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:10:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"code":"23505","constraint":"unique_status","detail":"Key (status)=(PREAPPROVAL) already exists.","file":"nbtinsert.c","length":206,"level":"error","line":"664","message":"Error calculating loan offer duplicate key value violates unique constraint \"unique_status\"","name":"error","query":"INSERT INTO application(client_id, creation_date, status) VALUES(146, '2023-08-07T11:37:14.027+00:00', 'PREAPPROVAL') RETURNING application_id","routine":"_bt_check_unique","schema":"public","service":"user-service","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"unique_status\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","table":"application"}
{"level":"error","name":"ConflictError","service":"user-service","statusCode":409}
{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:13:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:10:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"level":"error","name":"ConflictError","service":"user-service","statusCode":409}
{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:13:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:10:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"code":"22P02","file":"enum.c","length":122,"level":"error","line":"128","message":"Error calculating loan offer invalid input value for enum application_status_enum: \"СС_DENIED\"","name":"error","position":"104","query":"INSERT INTO application(client_id, creation_date, status) VALUES(148, '2023-08-07T11:42:14.170+00:00', 'СС_DENIED') RETURNING application_id","routine":"enum_in","service":"user-service","severity":"ERROR","stack":"error: invalid input value for enum application_status_enum: \"СС_DENIED\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"}
{"level":"error","name":"ConflictError","service":"user-service","statusCode":409}
{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:13:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:10:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"code":"23503","constraint":"fk_application_application_status","detail":"Key (status)=(CC_DENIED) is not present in table \"application_status\".","file":"ri_triggers.c","length":304,"level":"error","line":"2596","message":"Error calculating loan offer insert or update on table \"application\" violates foreign key constraint \"fk_application_application_status\"","name":"error","query":"INSERT INTO application(client_id, creation_date, status) VALUES(149, '2023-08-07T11:42:56.045+00:00', 'CC_DENIED') RETURNING application_id","routine":"ri_ReportViolation","schema":"public","service":"user-service","severity":"ERROR","stack":"error: insert or update on table \"application\" violates foreign key constraint \"fk_application_application_status\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","table":"application"}
{"level":"error","name":"ConflictError","service":"user-service","statusCode":409}
{"level":"error","message":"Error calculating loan offer Клиент с данным паспортом уже существует","name":"ConflictError","service":"user-service","stack":"ConflictError: Клиент с данным паспортом уже существует\n    at Task.<anonymous> (file:///usr/src/app/src/service/application.service.ts:13:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async addClientAndPassport (file:///usr/src/app/src/service/application.service.ts:10:20)\n    at async postApplication (file:///usr/src/app/src/controllers/application.controller.ts:14:26)","statusCode":409}
{"level":"error","message":"Error occurred: \"employment.position\" must be one of [MID_MANAGER, TOP_MANAGER, WORKER, OWNER]","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.workExperienceTotal\" must be greater than or equal to 12","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"code":0,"level":"error","message":"Ошибка при сохранении истории статуса: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: TypeError: Cannot read properties of undefined (reading 'employmentStatus')","service":"user-service"}
{"level":"error","message":"Error occurred: Cannot read properties of undefined (reading 'employmentStatus')","service":"user-service"}
{"level":"error","message":"Ошибка: error: more than one row returned by a subquery used as an expression","service":"user-service"}
{"level":"error","message":"Error occurred: more than one row returned by a subquery used as an expression","service":"user-service"}
{"level":"error","message":"Ошибка: error: more than one row returned by a subquery used as an expression","service":"user-service"}
{"level":"error","message":"Error occurred: more than one row returned by a subquery used as an expression","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.multiple\n    message: \"Multiple rows were not expected.\"\n    received: 2\n    query: \"SELECT id FROM employment_status WHERE employment_status = 'EMPLOYED'\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: error: duplicate key value violates unique constraint \"unique_status_id\"","service":"user-service"}
{"level":"error","message":"Error occurred: duplicate key value violates unique constraint \"unique_status_id\"","service":"user-service"}
{"level":"error","message":"Ошибка: error: duplicate key value violates unique constraint \"unique_status_id\"","service":"user-service"}
{"level":"error","message":"Error occurred: duplicate key value violates unique constraint \"unique_status_id\"","service":"user-service"}
{"level":"error","message":"Ошибка: error: duplicate key value violates unique constraint \"unique_status_id\"","service":"user-service"}
{"level":"error","message":"Error occurred: duplicate key value violates unique constraint \"unique_status_id\"","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: \"employment.workExperienceTotal\" must be greater than or equal to 12","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM employment_status WHERE employment_status = null\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: No data returned from the query.","service":"user-service"}
{"code":0,"level":"error","message":"Error in getChangeTypeIdFromDb: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"code":0,"level":"error","message":"Ошибка при сохранении истории статуса: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"code":0,"level":"error","message":"Error in updateApplicationStatusAndHistory: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"An error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"An error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Ошибка: ResourceNotFoundError: An error occurred: Multiple rows were not expected.","service":"user-service"}
{"level":"error","message":"Error occurred: An error occurred: Multiple rows were not expected.","service":"user-service"}
{"code":0,"level":"error","message":"Error in getChangeTypeIdFromDb: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"code":0,"level":"error","message":"Ошибка при сохранении истории статуса: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"code":0,"level":"error","message":"Error in updateApplicationStatusAndHistory: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"code":0,"level":"error","message":"Error in getChangeTypeIdFromDb: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"code":0,"level":"error","message":"Ошибка при сохранении истории статуса: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"code":0,"level":"error","message":"Error in updateApplicationStatusAndHistory: No data returned from the query.","name":"QueryResultError","query":"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';","received":0,"result":{"RowCtor":null,"_parsers":[null],"_types":{"_types":{"arrayParser":{},"builtins":{"ABSTIME":702,"ACLITEM":1033,"BIT":1560,"BOOL":16,"BPCHAR":1042,"BYTEA":17,"CHAR":18,"CID":29,"CIDR":650,"CIRCLE":718,"DATE":1082,"FLOAT4":700,"FLOAT8":701,"GTSVECTOR":3642,"INET":869,"INT2":21,"INT4":23,"INT8":20,"INTERVAL":1186,"JSON":114,"JSONB":3802,"MACADDR":829,"MACADDR8":774,"MONEY":790,"NUMERIC":1700,"OID":26,"PATH":602,"PG_DEPENDENCIES":3402,"PG_LSN":3220,"PG_NDISTINCT":3361,"PG_NODE_TREE":194,"POLYGON":604,"REFCURSOR":1790,"REGCLASS":2205,"REGCONFIG":3734,"REGDICTIONARY":3769,"REGNAMESPACE":4089,"REGOPER":2203,"REGOPERATOR":2204,"REGPROC":24,"REGPROCEDURE":2202,"REGROLE":4096,"REGTYPE":2206,"RELTIME":703,"SMGR":210,"TEXT":25,"TID":27,"TIME":1083,"TIMESTAMP":1114,"TIMESTAMPTZ":1184,"TIMETZ":1266,"TINTERVAL":704,"TSQUERY":3615,"TSVECTOR":3614,"TXID_SNAPSHOT":2970,"UUID":2950,"VARBIT":1562,"VARCHAR":1043,"XID":28,"XML":142}},"binary":{},"text":{}},"command":"SELECT","duration":0,"fields":[{"columnID":1,"dataTypeID":23,"dataTypeModifier":-1,"dataTypeSize":4,"format":"text","name":"id","tableID":16434}],"oid":null,"rowAsArray":false,"rowCount":0,"rows":[]},"service":"user-service","stack":"QueryResultError: No data returned from the query.\n    at Query.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/query.js:217:41)\n    at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:139:14)\n    at Client._handleReadyForQuery (/usr/src/app/node_modules/pg/lib/client.js:312:19)\n    at Connection.emit (node:events:520:28)\n    at Connection.emit (node:domain:475:12)\n    at /usr/src/app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:475:12)"}
{"level":"error","message":"Ошибка: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: \"SELECT id FROM change_type WHERE change_type = 'AUTOMATIC';\"\n}","service":"user-service"}
{"level":"error","message":"Error occurred: No data returned from the query.","service":"user-service"}
{"level":"error","message":"Error sending code: Code must be a 6-digit string","service":"user-service"}
{"level":"error","message":"Error sending code: Your code is incorrect.","service":"user-service"}
